// <auto-generated />
namespace EPMS.WorkFlow.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EPMS_Workflow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EPMS_Workflow));
        
        string IMigrationMetadata.Id
        {
            get { return "201710201902110_EPMS_Workflow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
